### ISSUE TITLE
confused about the marker

### ISSUE THREAD

**Issue by leenas233** [CarminLiu/ORB_SLAM2_aruco#2]
作者你好。最近我在看SPM-SLAM的论文，对里面的二维码估计相机相对位姿有点疑惑。
我的问题就是论文中的初始化过程，难道可以从一帧图像上得到相机和标记的相对位姿变换吗？这是怎么做到的呢？（不考虑所谓的Pose ambiguity ，我的意思指的就是难道可以从一张有二维码标记图片上得到相机的相对位姿吗，因为我是个初学者，这一点不太懂）

**Comment by CarminLiu** [comment]
可以从一帧图像上得到相机和标记的相对位姿变换，原理是利用了二维码四个角点都在同一平面的性质。
具体你可以看看十四讲上第七章对单应矩阵的描述，单应矩阵可以通过4对匹配点算出。

**Comment by CarminLiu** [comment]
得到的单应矩阵也要分解才能得到R和t，这里面就比较复杂了。
作者使用了Infinitesimal plane-based pose estimation这篇论文的方法，得到R，t。这个考虑了位姿模糊性的问题。

**Comment by leenas233** [comment]
好的好的，谢谢你
